const CORS_HEADERS={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"Content-Type"};
const VISION_MODEL="@cf/meta/llama-3.2-11b-vision-instruct";
const PSA_SCALE=`PSA 10: virtually perfect; razor-sharp corners and flawless surface. PSA 9: near-perfect, only very minor flaws. PSA 8: minor corner or edge wear permitted. PSA 7: slight surface or corner wear. PSA 6: noticeable imperfections such as small creases or moderate corner wear. PSA 5: moderate wear, minor creasing or surface issues. PSA 4: obvious wear including rounded corners or surface loss. PSA 3: heavy wear, creases or discoloration. PSA 2: significant damage such as major creases or staining. PSA 1: severe damage, tears, missing paper or heavy creasing.`;

export default{async fetch(request,env){if(request.method==="OPTIONS")return new Response(null,{headers:CORS_HEADERS});if(request.method!=="POST")return new Response("Method not allowed",{status:405,headers:CORS_HEADERS});const url=new URL(request.url);try{if(url.pathname==="/identify-card")return await identifyCard(request,env);if(url.pathname==="/grade-card")return await gradeCard(request,env);if(url.pathname==="/estimate-value")return await estimateValue(request,env);return new Response("Not found",{status:404,headers:CORS_HEADERS})}catch(error){console.error(error);return jsonResponse({error:error?.message||"The TrueCard service encountered an error."},500)}}};

async function identifyCard(request,env){const formData=await request.formData();const image=formData.get("image");if(!image)return jsonResponse({error:"Missing image"},400);const f=new FormData();f.append("image",image);const r=await fetch("https://api.cardsight.ai/v1/identify/card",{method:"POST",headers:{"X-API-Key":env.CARDSIGHT_API_KEY},body:f});const result=await r.text();return new Response(result,{status:r.status,headers:{...CORS_HEADERS,"Content-Type":"application/json"}})}

async function gradeCard(request,env){if(!env.AI)return jsonResponse({error:"Workers AI binding is not configured."},500);const fd=await request.formData();const front=fd.get("front"),back=fd.get("back");if(!front||typeof front.arrayBuffer!=="function")return jsonResponse({error:"A front card image is required."},400);const fa=await analyzeCardSide(env.AI,front,"front");const ba=back&&typeof back.arrayBuffer==="function"?await analyzeCardSide(env.AI,back,"back"):null;const combined=await combineGradeAnalyses(env.AI,fa,ba);return jsonResponse({suggested_grade:combined.suggested_grade||"Unable to estimate",grade_explanation:combined.grade_explanation||"Not enough detail for a reliable estimate.",centering:combined.centering||"",corners:combined.corners||"",edges:combined.edges||"",surface:combined.surface||"",back:combined.back||"No back image was supplied.",confidence:combined.confidence||"Low",disclaimer:"Photo-based estimate only. This is not a professional grade."})}

async function analyzeCardSide(ai,imageFile,side){const imageBytes=Array.from(new Uint8Array(await imageFile.arrayBuffer()));const prompt=`Inspect ONLY the PHYSICAL CONDITION of the ${side} side of this trading card for grading. Ignore the player, team, statistics, text, artwork, background, colors, logos and design completely.

CRITICAL CORNER INSPECTION: Examine ALL FOUR corners independently: TOP-LEFT, TOP-RIGHT, BOTTOM-LEFT, BOTTOM-RIGHT. Look closely at the actual outermost corner for whitening, chipping, rounding, bends, compression, dings, dents and edge/corner wear. A subtle but visible nick or whitening is still wear. Do not say corners are undamaged until each of the four has been examined.

Also inspect centering, all four edges, and the surface for scratches, dings, dents, indentations, wrinkles, creases, stains, discoloration and print defects.

Evidence rules: report ONLY physical damage that is actually visible. Never invent defects. Do not mistake shadows, glare, reflections, normal printing, sleeves, holders or compression for damage. If uncertain whether something is damage, put it in uncertain_observations and do not treat it as confirmed. Never infer damage from the opposite side. If no crease is visibly supported, do not report a crease.

Return ONLY JSON:
{"side":"${side}","centering":"brief","corners":{"top_left":"brief","top_right":"brief","bottom_left":"brief","bottom_right":"brief","summary":"brief meaningful corner condition"},"edges":"brief meaningful edge condition","surface":"brief meaningful surface condition","confirmed_defects":["short visible defect and location"],"uncertain_observations":["short uncertain observation"]}

Do not describe anything except physical condition.`;const response=await ai.run(VISION_MODEL,{prompt,image:imageBytes,max_tokens:600,temperature:0.02});console.log(`Workers AI raw ${side} response:`,JSON.stringify(response,null,2));return parseSideAnalysis(response,side)}

async function combineGradeAnalyses(ai,frontAnalysis,backAnalysis){const prompt=`You are the final trading-card grading decision-maker. Use ONLY physical-condition evidence below.

PSA FRAMEWORK: ${PSA_SCALE}

FRONT: ${JSON.stringify(frontAnalysis)}
BACK: ${backAnalysis?JSON.stringify(backAnalysis):"No back photograph supplied."}

Rules:
- PSA framework governs the grade.
- Never invent a defect.
- Ignore uncertain observations.
- Consider ALL FOUR corners individually. If source evidence says a corner has visible whitening, chipping, rounding, a nick, ding or other wear, the final corner assessment MUST acknowledge it.
- Never state "corners are not damaged" or equivalent when any source corner has confirmed visible damage.
- A confirmed crease is incompatible with PSA 7-10; constrain the estimate to PSA 6 or below.
- PSA 10 requires virtually perfect condition; PSA 9 is near-perfect; PSA 8 permits minor corner/edge wear; PSA 7 permits slight surface/corner wear.
- Do not lower the grade for a defect that is not actually visible.
- Do not claim hidden damage is absent.
- Return a range no wider than one numerical grade.

USER OUTPUT MUST BE CONCISE. Never mention player, team, statistics, text, artwork, background, colors, logos, design, photograph contents, or AI analysis. Report only condition information that matters to the grade. Do not repeat normal observations.

Return ONLY:
{"suggested_grade":"7-8","grade_explanation":"1-2 short sentences using only key condition issues","centering":"one short sentence","corners":"one short sentence naming meaningful corner wear, or No significant visible corner wear","edges":"one short sentence naming meaningful edge wear, or No significant visible edge wear","surface":"one short sentence naming meaningful surface issues, or No significant visible surface damage","back":"one short sentence about meaningful visible back condition","confidence":"High, Medium, or Low"}`;const response=await ai.run(VISION_MODEL,{prompt,max_tokens:350,temperature:0.02});console.log("Workers AI combined response:",JSON.stringify(response,null,2));return enforceGradeConsistency(parseModelJson(response),frontAnalysis,backAnalysis)}

function enforceGradeConsistency(result,frontAnalysis,backAnalysis){const analyses=[frontAnalysis,backAnalysis].filter(Boolean);const confirmed=analyses.flatMap(a=>Array.isArray(a?.confirmed_defects)?a.confirmed_defects:[]);if(confirmed.some(d=>/\b(crease|creased|wrinkle|wrinkled)\b/i.test(String(d)))){const range=parseGradeRange(result?.suggested_grade);if(range&&range.high>6)return {...result,suggested_grade:"5-6",grade_explanation:"A confirmed visible crease was reported, so the estimate is constrained to the PSA 6-or-below range."}}return result}
function parseGradeRange(value){const n=String(value||"").match(/\d+(?:\.\d+)?/g)?.map(Number)||[];if(!n.length)return null;if(n.length===1)return{low:n[0],high:n[0]};return{low:Math.min(n[0],n[1]),high:Math.max(n[0],n[1])}}

async function estimateValue(request,env){if(!env.GEMINI_API_KEY)return jsonResponse({error:"Gemini API key is not configured."},500);const card=await request.json();if(!card?.player)return jsonResponse({error:"Player or card name is required."},400);const cardDescription=[card.year,card.player,card.manufacturer,card.setName,card.releaseName,card.cardNumber?`#${card.cardNumber}`:"",card.gradingCompany,card.professionalGrade?`grade ${card.professionalGrade}`:"",!card.professionalGrade&&card.suggestedGrade?`estimated condition ${card.suggestedGrade}`:"",card.sport].filter(Boolean).join(" ");const prompt=`Estimate current US dollar market value for this trading card: ${cardDescription}. Use Google Search and recent sold/completed sales. Match year, player, set, number, variation, company and grade. Do not treat asking prices as sold prices. Do not use SportsCardsPro. Do not invent sales, prices, dates or sources. Return JSON with estimated_value, low_estimate, high_estimate, currency, confidence, summary, comparables_found, search_description.`;const r=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":env.GEMINI_API_KEY},body:JSON.stringify({model:"gemini-3.5-flash",input:prompt,tools:[{type:"google_search"}]})});const gr=await r.json();if(!r.ok)throw new Error(gr?.error?.message||"Gemini could not complete the value search.");const mo=gr.steps?.find(s=>s.type==="model_output"),tb=mo?.content?.find(b=>b.type==="text");if(!tb?.text)throw new Error("Gemini returned an empty value estimate.");const estimate=parseGeminiJson(tb.text),sources=[];for(const s of gr.steps||[]){if(s.type!=="model_output")continue;for(const b of s.content||[])for(const a of b.annotations||[])if(a.type==="url_citation"&&a.url)sources.push({title:a.title||"Internet source",url:a.url})}const uniqueSources=Array.from(new Map(sources.map(s=>[s.url,s])).values()).slice(0,8);return jsonResponse({estimated_value:Number(estimate.estimated_value)||0,low_estimate:Number(estimate.low_estimate)||0,high_estimate:Number(estimate.high_estimate)||0,currency:"USD",confidence:estimate.confidence||"Low",summary:estimate.summary||"Internet-based estimate using available comparable information.",comparables_found:Number(estimate.comparables_found)||0,search_description:estimate.search_description||cardDescription,sources:uniqueSources,estimated_at:new Date().toISOString(),disclaimer:"Internet-based estimate only. Market prices and card condition can change the actual selling price."})}
function parseGeminiJson(raw){const cleaned=String(raw).replace(/`json/gi,"").replace(/`/g,"").trim();try{return JSON.parse(cleaned)}catch{const f=cleaned.indexOf("{"),l=cleaned.lastIndexOf("}");if(f!==-1&&l>f)return JSON.parse(cleaned.slice(f,l+1));throw new Error("Gemini returned an unreadable value estimate.")}}
function parseSideAnalysis(result,side){try{return parseModelJson(result)}catch(error){const raw=typeof result==="string"?result:result?.response??result?.result?.response??result?.result??"";const text=String(raw).trim();if(!text)throw error;console.warn(`Workers AI returned non-JSON ${side} analysis. Using text fallback.`);return{side,centering:"",corners:{top_left:"",top_right:"",bottom_left:"",bottom_right:"",summary:""},edges:"",surface:text,confirmed_defects:[],uncertain_observations:[]}}}
function parseModelJson(result){const raw=typeof result==="string"?result:result?.response??result?.result?.response??result?.result??result;if(raw===null||raw===undefined||raw==="")throw new Error("The AI model returned an empty response.");if(typeof raw==="object")return raw;const cleaned=String(raw).replace(/`json/gi,"").replace(/`/g,"").trim();try{return JSON.parse(cleaned)}catch{}const jsonText=extractFirstJsonObject(cleaned);if(jsonText){try{return JSON.parse(jsonText)}catch(error){console.error("Extracted grading JSON could not be parsed:",jsonText,error)}}throw new Error("The AI model returned an unreadable grading result.")}
function extractFirstJsonObject(text){const startIndex=text.indexOf("{");if(startIndex===-1)return null;let depth=0,insideString=false,escaped=false;for(let i=startIndex;i<text.length;i++){const c=text[i];if(insideString){if(escaped){escaped=false;continue}if(c==="\\"){escaped=true;continue}if(c==='"')insideString=false;continue}if(c==='"'){insideString=true;continue}if(c==="{"){depth++;continue}if(c==="}"){depth--;if(depth===0)return text.slice(startIndex,i+1)}}return null}
function jsonResponse(body,status=200){return new Response(JSON.stringify(body),{status,headers:{...CORS_HEADERS,"Content-Type":"application/json"}})}